[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
name = "Graph Wavenet"
version = "0.1.0"
description = "Graph Wavenet Implementation"
author = ""
